### PR TITLE
feature (block params): reimplementation, block params support, pace, first, last

### PR DESCRIPTION
**Pull request by BjornMelgaard**

### CODE REVIEW

**Comment by BjornMelgaard** [comment]
1 sec

**Comment by BjornMelgaard** [comment]
all, done

**Comment by BjornMelgaard** [comment]
can be merged

**Comment by BjornMelgaard** [comment]
@jonschlinkert will you merge it? 

it fixes https://github.com/helpers/handlebars-helper-repeat/issues/5
and covers this pr https://github.com/helpers/handlebars-helper-repeat/pull/2

**Comment by doowb** [comment]
@BjornMelgaard thanks for the PR, I appreciate it and we'll review when we have a chance. There are more changes here than I expected.

**Comment by BjornMelgaard** [comment]
Ok)

**Comment by jonschlinkert** [comment]
@BjornMelgaard thanks for the PR, I just published a new version that credits you in the commit. I used some ideas from this PR but made a few changes. Thanks again!

**Pull request closed without merging**
